### ISSUE TITLE
"Unknown error" in Rec Phrase flow

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-android#312] opened 2018-11-28 09:27 UTC
**Describe the bug**
Wehn creating second Safe, connecting browser extension, adter

**To Reproduce**
1. Go to 'Create a new Safe'
2. Connect browser extension
3. Record and confirm recovery phrase
4. Hit 'Submit'

**Expected behavior**
Submit is supposed to take user to screen to make first deposit into new safe.

**Screenshots**
![photo on 28 11 18 at 10 19](https://user-images.githubusercontent.com/39806845/49141955-0dac3180-f2f8-11e8-869b-d1f1833e0d82.jpg)

**Smartphone (please complete the following information):**
 - Device: Moto G5S Plus
 - Android Version: 8.1.0
 - App Version 0.8.0-rinkeby

**Comment by rmeissner** [comment] 2018-11-28 09:36
If the browser extension was connected, what version of tge browser extension was used?

Also it seems the **describe the bug** section is cut off

**Comment by rmeissner** [comment] 2018-11-28 09:45
I cannot reproduce this issue. We will implement more verbose error messages for non-production builds. 

Can you reproduce this error for a clean install? (clearing all app data has the same effect)

**Comment by Mettenim** [comment] 2018-11-28 11:53
I cannot reproduce the bug after reinstall.

**Comment by rmeissner** [comment] 2018-11-28 12:12
Ok. I will close the issue for now and I try to get the verbose error reporting in this week. This would allow us to have more information if that happens again on the Rinkeby version.

**Closed by rmeissner** 2018-11-28 12:12 UTC
Labels: needs research
