### ISSUE TITLE
Safe Settings: Edit safe local name

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#728] opened 2020-07-13 15:16 UTC
**Describe the solution you'd like**
The local name field in the Safe Settings screen should be clickable and lead to the safe name setting screen (same as when adding a safe).

Upon back navigation, the field should display updated.

**Comment by liliya-soroka** [comment] 2020-07-24 13:53
closed as duplicate of https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/750

App version 1.12.1 -72 (576)

**Closed by liliya-soroka** 2020-07-24 13:53 UTC
