### ISSUE TITLE
[Android] Tx list is scrolled up after navigation back from the tx details

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#997] opened 2020-10-15 12:56 UTC
**Describe the bug**
Tx list is scrolled up after navigation back from the tx details , the user has to scroll down each time if he wants to check a few tx on the previous page

**To Reproduce**
1. Add safe 0xD2b3D480Db9Fb08Ea55c349C0299b81892F31544
2. Scroll down to the tx with 560 nonce
3. Open tx details
4. Go back from the tx details

**Expected behavior**
The tx list should not be scrolled up each time after tx details opening

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 11
 - App Version 2.3.0 - 1282rc

**Environment**
Prod mainnet
**Additional context**

**Comment by tschubotz** [comment] 2020-10-16 11:27
This is unfortunately currently a feature, not a bug.

Will be changed with gnosis/safe#354

So I'll close this one.

**Closed by tschubotz** 2020-10-16 11:27 UTC
Labels: bug
