### ISSUE TITLE
Use Collectibles endpoint from the client gateway

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#1046] opened 2020-11-05 12:53 UTC
The client gateway relays the collectibles endpoint from the transaction service adding a layer of caching to the request and alleviating the transaction service.

There are no changes to be made to the models returned by the endpoint. Only the service to which the request is sent.
The gateway endpoint: `/v1/safes/<safe_address>/collectibles`

May need to adjust the tests

**Comment by liliya-soroka** [comment] 2020-11-13 12:51
Reopened:
"An error occurred" message appears instead of collectibles list for the safe 0xD2b3D480Db9Fb08Ea55c349C0299b81892F31544 , prod , mainnet
Note: the safe contains spam erc721 tokens that are marked as Unknow
app version 2.4.0 -1475

**Comment by liliya-soroka** [comment] 2020-11-13 12:55
I think that the issue https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1073 and https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1046 may be connected, as I can not add the same safes that have problems with collectables

**Comment by biafra23** [comment] 2020-11-19 08:39
@liliya-soroka I cannot reproduce this on 2.5.0-1531 (prod mainnet)

**Comment by liliya-soroka** [comment] 2020-11-19 14:25
Verified
the issue was with the urls for staging and prod mainnet
app version 2.6.0 -1534rc

**Closed by liliya-soroka** 2020-11-19 14:25 UTC
Labels: refactoring
